from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('g1632', src, depend = ['G1632_USING_EXAMPLE'], CPPPATH = CPPPATH)

Return('group')
